### ISSUE TITLE
Dependency conflict (numpy version)

### ISSUE THREAD

**Issue by qathom** [akestoridis/mcdm#1]
Hello,
First of all, thanks a lot for creating mcdm!
I'm now using mcdm in one of my projects but I'm facing some conflicting versions.
I could see that the [numpy requirement must be 1.21.3](https://github.com/akestoridis/mcdm/blob/master/requirements.txt#L1)
Is it possible to give more "flexibility" by using numpy>=1.19 in requirements.txt?
I'm pretty sure that older minor versions are working with mcdm.

**Comment by akestoridis** [comment]
Hello!

The [`requirements.txt`](https://github.com/akestoridis/mcdm/blob/ce0535e30a15e0058c4f3a1949bcadee4adbdd53/requirements.txt) file is provided for users that are interested in installing the version of NumPy that was used during the latest testing of the `mcdm` package. The range of supported NumPy versions is defined in the [`mcdm/_metadata.py`](https://github.com/akestoridis/mcdm/blob/ce0535e30a15e0058c4f3a1949bcadee4adbdd53/mcdm/_metadata.py#L55-L57) file, which is currently defined as `numpy>=1.21.3, <2`.

If you have an older version of NumPy already installed on your system and you cannot or do not want to upgrade it, then you can avoid the dependency conflict by installing the `mcdm` package in a Python 3 virtual environment as follows:
```console
$ python3 -m venv venv/
$ source venv/bin/activate
(venv) $ pip install --upgrade pip
(venv) $ pip install mcdm
```

**Comment by qathom** [comment]
Hello, thank you for taking the time to guide me through the installation!

This was indeed my problem (numpy version) since another dependency in my project requires numpy <= 1.2 
I forced the installation of numpy 1.19 and didn't face any issue with mcdm.
I didn't read all the code but I'm pretty sure that mcdm might support older versions of numpy (Numpy 1.19.0 has been released [Jun 20, 2020](https://pypi.org/project/numpy/1.19.0/)).
Isn't it better to set a requirement range for the version in requirements.txt instead of exact match?
For example: `numpy = ">=1.20.0,<2"`

Out of context: thanks for providing the links to the articles explaining the developed methods, the usage is clear!

**Comment by akestoridis** [comment]
No problem!

The range of NumPy versions in the `mcdm/_metadata.py` file is defined to accept (a) the NumPy version that was last used to test the `mcdm` package and (b) future minor or patch NumPy versions since they should be backwards compatible. Older NumPy versions are not included in that range because they were not used during the latest testing of the `mcdm` package (even though some of them would most likely work as well). If, for some reason, a future minor or patch NumPy version contains breaking changes, users can use the `requirements.txt` file to install the NumPy version that was used during the latest testing of the `mcdm` package as follows:
```console
$ git clone https://github.com/akestoridis/mcdm.git
$ cd mcdm/
$ python3 -m venv venv/
$ source venv/bin/activate
(venv) $ pip install --upgrade pip
(venv) $ pip install -r requirements.txt
(venv) $ pip install .
```
I added additional installation instructions in the README file in case anyone else faces a similar issue (commit 2511f42767638c466183351fdc8ffd9290d3b391).

Of course, if you are forced to use an older version of NumPy, you could also install an older version of the `mcdm` package that supports that older version of NumPy.
